[uwsgi]
socket = 0.0.0.0:8000
# http://localhost:8000/
protocol = http
module = uWSGI:app
plugin = python3

# Only needed when you want thread support without setting a thread count
# enable-threads = true

# master = true
# processes = 4
# threads = 2
